#---+----------------------------------------------------------------------------------------------------+---#
#                                        BaseKit - Main Configuration                                        #
#---+----------------------------------------------------------------------------------------------------+---#
#                                                                                                            #
# About *built-in placeholders*:                                                                             #
#   The supported built-in placeholders vary depending on the configuration option. Refer to the comments    #
#   for the corresponding configuration option for details.                                                  #
#                                                                                                            #
# About *sounds*:                                                                                            #
# This plugin utilizes XSeries for cross-version compatibility. XSound is responsible for the cross-version  #
# implementation of sound effects. For a complete list of sound effects, please visit:                       #
# https://github.com/CryptoMorin/XSeries/blob/master/core/src/main/java/com/cryptomorin/xseries/XSound.java  #
#                                                                                                            #
#---+----------------------------------------------------------------------------------------------------+---#

# |------------------------------------------------------------------|
# |                         Config Version                           |
# |                       ------------------                         |
# | This option is used for detect whether your configuration file   |
# | is outdated.                                                     |
# |------------------------------------------------------------------|
# | WARNING: Do not modify this option only if you know what you are |
# |          doing!                                                  |
# |------------------------------------------------------------------|
config-version: 1

# |------------------------------------------------------------------|
# |                          Update Checker                          |
# |                       -------------------                        |
# | The plugin will send a notification to the server every time it  |
# | is started or when a player with administrator privileges enters |
# | the server.                                                      |
# | Check will be performed every 10 minutes.                        |
# |------------------------------------------------------------------|
update-checker: true

# |------------------------------------------------------------------|
# |                       PlaceholderAPI Hook                        |
# |                     -----------------------                      |
# | By enabling this option, the plugin will automatically detect    |
# | whether the server has installed PlaceholderAPI. If disabled,    |
# | all placeholders related to PlaceholderAPI will be unavailable,  |
# | whether PlaceholderAPI is installed or not.                      |
# |------------------------------------------------------------------|
placeholderapi-hook: true

# |------------------------------------------------------------------|
# |                           Player Join                            |
# |                         ---------------                          |
# | Message/sound effect to be triggered when a player joins the     |
# | server.                                                          |
# |------------------------------------------------------------------|
# | Placeholders:                                                    |
# |   + %%player%% - Player name                                     |
# |------------------------------------------------------------------|
player-join:
  enabled: true
  message: "<dark_gray>[</dark_gray><dark_green>+</dark_green><dark_gray>]</dark_gray> <white>%%player%% has joined the server!</white>"
  sound: BLOCK_NOTE_BLOCK_PLING,1,2

# |------------------------------------------------------------------|
# |                           Player Quit                            |
# |                         ---------------                          |
# | Message/sound effect to be triggered when a player leaves the    |
# | server.                                                          |
# |------------------------------------------------------------------|
# | Placeholders:                                                    |
# |   + %%player%% - Player name                                     |
# |------------------------------------------------------------------|
player-quit:
  enabled: true
  message: "<dark_gray>[</dark_gray><dark_green>+</dark_green><dark_gray>]</dark_gray> <white>%%player%% has left the server!</white>"
  sound: BLOCK_NOTE_BLOCK_PLING,1,0.5

# |------------------------------------------------------------------|
# |                        Disabled Commands                         |
# |                      ---------------------                       |
# | Prohibit players from executing confidential commands.           |
# |------------------------------------------------------------------|
disabled-commands:
  enabled: true
  prompt-message: "<red>This command is disabled on this server! (/%%command%%)</red>"
  bypass-permission: "basekit.bypass.disabled-commands"
  commands:
    - bukkit:plugins
    - plugins
    - bukkit:version
    - version
    - ver
    - bukkit:pl
    - pl
    - icanhasbukkit

# |------------------------------------------------------------------|
# |                         Welcome Message                          |
# |                       -------------------                        |
# | When a player joins the server, the welcome message will be sent |
# | to that player. If the player joins the server for the first     |
# | time, only the first-join message will be sent.                  |
# |------------------------------------------------------------------|
# | Placeholders:                                                    |
# |   + %%player%% - Player name                                     |
# |------------------------------------------------------------------|
welcome-message:
  enabled: true
  welcome-message: |-
    <gold>--------------------------------------------------</gold>
    <green>Welcome back to</green> <light_purple>Your Server</light_purple> <green>%%player%%!</green>
    <gold>--------------------------------------------------</gold>
  first-join-message: |-
    <gold>--------------------------------------------------</gold>
    <green>Welcome to</green> <light_purple>Your Server</light_purple> <green>%%player%%!</green>
    <yellow>This is your first time to join the server.</yellow>
    <yellow>Hope you enjoy your play!</yellow>
    <gold>--------------------------------------------------</gold>

# |------------------------------------------------------------------|
# |                          Help Command                            |
# |                        ----------------                          |
# | This will replace the vanilla help command to your custom help   |
# | message. If enabled, whether help command is listed in           |
# | "disabled-commands" or not, the command still can be executed.   |
# |------------------------------------------------------------------|
# | Placeholders:                                                    |
# |   + %%player%% - Player name                                     |
# |------------------------------------------------------------------|
help-command:
  enabled: true
  message: |-
    <yellow>Server Help:</yellow>
    <aqua> - This is the help message of your server.</aqua>
    <aqua> - Please configure it in config.yml.</aqua>

# |------------------------------------------------------------------|
# |                              Chat                                |
# |                            --------                              |
# | Change the vanilla chat format, block similar chats, and more.   |
# |------------------------------------------------------------------|
# | Placeholders:                                                    |
# |   + %%player%% - Player name                                     |
# |   + %%message%% - Message content                                |
# |------------------------------------------------------------------|
chat:
  message-format:
    enabled: true
    format: "<yellow>%%player%%</yellow><white>: %%message%%</white>"
  block-similar-message:
    enabled: true
    similarity: 0.7
    prompt-message: "<red>You cannot send the same message twice!</red>"
  block-bad-words:
    enabled: true
    prompt-message: "<red>Your message may contains bad words!</red>"
    key-words:
      - "fuck"
      - "shit"